# Dependabot配置：
# https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
    # 维护Gradle依赖项的依赖项
    -   package-ecosystem: "gradle"
        directory: "/"
        schedule:
            interval: "daily"
    # 维护GitHub Actions的依赖项
    -   package-ecosystem: "github-actions"
        directory: "/"
        schedule:
            interval: "daily"